name: rhythm_files
description: A Flutter package that provides a simple and easy-to-use file picker with a built-in UI.
version: 1.0.2
homepage: https://github.com/CodemonkHQ/rhythm_files

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  video_compress: ^3.1.0
  mime: ^1.0.4
  file_previewer: ^0.0.6
  file_picker: ^4.6.1
  cloudinary_flutter: ^0.9.0
  cloudinary_public: ^0.13.0
  image_cropper: ^3.0.2
  image_picker: ^0.8.7+1
  flutter_native_image: ^0.0.6+1
  fluentui_system_icons: ^1.1.198
  path_provider: ^2.0.14
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: